@BaseUrl = http://localhost:5112
@AuthToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsIlVzZXJJZCI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoi57O757ufIiwiV29ya05vIjoic3lzdGVtIiwiZXhwIjoxNzg1NzU4ODgyLCJpc3MiOiJGdWxsYW50aS1TZXJ2aWNlIiwiYXVkIjoiRnVsbGFudGktU2VydmljZSJ9.eNICCbawN84Ojf8zWo0BtmqJIjhxADEKkbxws8-GhcU

GET {{BaseUrl}}/fgms/pc/user/list
Authorization: {{AuthToken}}